name: Example Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  get-sha:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short SHA
        id: set_short_sha
        run: |
          echo GIT_SHORT_SHA=$("${{ github.sha }}".SubString(0, 7))
          echo "::set-output name=GREET::$GIT_SHORT_SHA"        
         
      - name: Print short SHA
        run: |
          echo %GIT_SHORT_SHA%
        shell: cmd
                
  test-sha:
    runs-on: ubuntu-latest
    needs: get-sha
    steps:
      - name: Test SHORT_SHA
        run: |
          echo "${{ steps.set_short_sha.outputs.GREET }}"      
        
