name: Example Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  get-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short SHA
        run:  echo "SHORT_SHA=$(echo ${GITHUB_SHA})" >> $GITHUB_ENV

      - name: Display SHORT_SHA  
        run: echo "The short SHA is: ${SHORT_SHA}"
