name: Example Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  get-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short SHA
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_ENV

  job1:
    needs: get-sha
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use short SHA in job1
        run: |
          echo "The short SHA from job1 is ${SHORT_SHA}"
          
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use short SHA in job2
        run: |
          echo "The short SHA from job2 is ${{ env.SHORT_SHA }}"
          
