name: Example Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SHORT_SHA: ""
jobs:
  get-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short SHA
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_ENV

      - name: Display SHORT_SHA  
        run: echo "The short SHA is: ${{ env.SHORT_SHA }}"
  test-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Test SHORT_SHA
        run: echo "The short SHA is: ${{ env.SHORT_SHA }}"
