name: Example Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SHORT_SHA: "abc"
  
jobs:
  get-sha:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short SHA
        run: echo "GIT_SHORT_SHA=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_ENV
        
      - name: Print short SHA
        run: echo $env:GIT_SHORT_SHA
        
      - name: Print short SHA
        run: echo ${{ env.GIT_SHORT_SHA }}
        
  test-sha:
    runs-on: ubuntu-latest
    needs: get-sha
    steps:
      - name: Test SHORT_SHA
        run:  echo "sha=${{ env.GIT_SHORT_SHA }}" >> $env:GITHUB_ENV
        
          
