name: Example Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SHORT_SHA: "abc"
  
jobs:
  get-sha:
    runs-on: windows-latest
    outputs:  
      git_short_sha: ${{ steps.set_short_sha.outputs.git_short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short SHA
        id: set_short_sha
        run: |
          echo "GIT_SHORT_SHA=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_ENV
          echo "::set-output name=short::${{ env.GIT_SHORT_SHA }}
          
      - name: Print short SHA
        run: echo $env:GIT_SHORT_SHA
        
      - name: Print short SHA
        run: echo ${{ env.GIT_SHORT_SHA }}
        
  test-sha:
    runs-on: ubuntu-latest
    needs: get-sha
    steps:
      - name: Test SHORT_SHA
        run: |
          echo "The short SHA from job1 is: $short"
        
          
