name: Example Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  getsha:
    runs-on: windows-latest
    outputs:
      GIT_SHA: ${{ steps.get_sha.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short SHA
        id: get_sha
        run: |
          $GIT_SHORT_SHA= $("${{ github.sha }}".SubString(0, 7))
          echo "Git short sha is $GIT_SHORT_SHA"
          echo "::set-output name=sha::$GIT_SHORT_SHA"
                        
  testsha:
    runs-on: windows-latest
    needs: getsha
    steps:      
      - name: Test SHORT_SHA
        run: |
          echo "The commit hash from the build job is ${{ needs.getsha.outputs.GIT_SHA }}"    

  TESTING:
    runs-on: windows-latest
    needs: [ testsha, getsha ]
    steps:      
      - name: Again test SHORT_SHA
        run: |
          echo "${{ needs.getsha.outputs.GIT_SHA }}"
        
